/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudiobookRouteImport } from './routes/audiobook'
import { Route as AuthorWebsiteRouteImport } from './routes/author-website'
import { Route as BookCoverDesignRouteImport } from './routes/book-cover-design'
import { Route as BookEditingRouteImport } from './routes/book-editing'
import { Route as BookFormattingRouteImport } from './routes/book-formatting'
import { Route as BookIllustrationRouteImport } from './routes/book-illustration'
import { Route as BookMarketingRouteImport } from './routes/book-marketing'
import { Route as BookPrintingRouteImport } from './routes/book-printing'
import { Route as BookVideoTrailerRouteImport } from './routes/book-video-trailer'
import { Route as ChildrensBookPublishersRouteImport } from './routes/childrens-book-publishers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GetAQuoteRouteImport } from './routes/get-a-quote'
import { Route as GhostWritingRouteImport } from './routes/ghost-writing'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PublishBookRouteImport } from './routes/publish-book'
import { Route as TestimonialsRouteImport } from './routes/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiobookRoute = AudiobookRouteImport.update({
  id: '/audiobook',
  path: '/audiobook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorWebsiteRoute = AuthorWebsiteRouteImport.update({
  id: '/author-website',
  path: '/author-website',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCoverDesignRoute = BookCoverDesignRouteImport.update({
  id: '/book-cover-design',
  path: '/book-cover-design',
  getParentRoute: () => rootRouteImport,
} as any)
const BookEditingRoute = BookEditingRouteImport.update({
  id: '/book-editing',
  path: '/book-editing',
  getParentRoute: () => rootRouteImport,
} as any)
const BookFormattingRoute = BookFormattingRouteImport.update({
  id: '/book-formatting',
  path: '/book-formatting',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIllustrationRoute = BookIllustrationRouteImport.update({
  id: '/book-illustration',
  path: '/book-illustration',
  getParentRoute: () => rootRouteImport,
} as any)
const BookMarketingRoute = BookMarketingRouteImport.update({
  id: '/book-marketing',
  path: '/book-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const BookPrintingRoute = BookPrintingRouteImport.update({
  id: '/book-printing',
  path: '/book-printing',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVideoTrailerRoute = BookVideoTrailerRouteImport.update({
  id: '/book-video-trailer',
  path: '/book-video-trailer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrensBookPublishersRoute = ChildrensBookPublishersRouteImport.update({
  id: '/childrens-book-publishers',
  path: '/childrens-book-publishers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAQuoteRoute = GetAQuoteRouteImport.update({
  id: '/get-a-quote',
  path: '/get-a-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostWritingRoute = GhostWritingRouteImport.update({
  id: '/ghost-writing',
  path: '/ghost-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishBookRoute = PublishBookRouteImport.update({
  id: '/publish-book',
  path: '/publish-book',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiobook': typeof AudiobookRoute
  '/author-website': typeof AuthorWebsiteRoute
  '/book-cover-design': typeof BookCoverDesignRoute
  '/book-editing': typeof BookEditingRoute
  '/book-formatting': typeof BookFormattingRoute
  '/book-illustration': typeof BookIllustrationRoute
  '/book-marketing': typeof BookMarketingRoute
  '/book-printing': typeof BookPrintingRoute
  '/book-video-trailer': typeof BookVideoTrailerRoute
  '/childrens-book-publishers': typeof ChildrensBookPublishersRoute
  '/contact': typeof ContactRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/ghost-writing': typeof GhostWritingRoute
  '/our-story': typeof OurStoryRoute
  '/portfolio': typeof PortfolioRoute
  '/publish-book': typeof PublishBookRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiobook': typeof AudiobookRoute
  '/author-website': typeof AuthorWebsiteRoute
  '/book-cover-design': typeof BookCoverDesignRoute
  '/book-editing': typeof BookEditingRoute
  '/book-formatting': typeof BookFormattingRoute
  '/book-illustration': typeof BookIllustrationRoute
  '/book-marketing': typeof BookMarketingRoute
  '/book-printing': typeof BookPrintingRoute
  '/book-video-trailer': typeof BookVideoTrailerRoute
  '/childrens-book-publishers': typeof ChildrensBookPublishersRoute
  '/contact': typeof ContactRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/ghost-writing': typeof GhostWritingRoute
  '/our-story': typeof OurStoryRoute
  '/portfolio': typeof PortfolioRoute
  '/publish-book': typeof PublishBookRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audiobook': typeof AudiobookRoute
  '/author-website': typeof AuthorWebsiteRoute
  '/book-cover-design': typeof BookCoverDesignRoute
  '/book-editing': typeof BookEditingRoute
  '/book-formatting': typeof BookFormattingRoute
  '/book-illustration': typeof BookIllustrationRoute
  '/book-marketing': typeof BookMarketingRoute
  '/book-printing': typeof BookPrintingRoute
  '/book-video-trailer': typeof BookVideoTrailerRoute
  '/childrens-book-publishers': typeof ChildrensBookPublishersRoute
  '/contact': typeof ContactRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/ghost-writing': typeof GhostWritingRoute
  '/our-story': typeof OurStoryRoute
  '/portfolio': typeof PortfolioRoute
  '/publish-book': typeof PublishBookRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audiobook'
    | '/author-website'
    | '/book-cover-design'
    | '/book-editing'
    | '/book-formatting'
    | '/book-illustration'
    | '/book-marketing'
    | '/book-printing'
    | '/book-video-trailer'
    | '/childrens-book-publishers'
    | '/contact'
    | '/get-a-quote'
    | '/ghost-writing'
    | '/our-story'
    | '/portfolio'
    | '/publish-book'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audiobook'
    | '/author-website'
    | '/book-cover-design'
    | '/book-editing'
    | '/book-formatting'
    | '/book-illustration'
    | '/book-marketing'
    | '/book-printing'
    | '/book-video-trailer'
    | '/childrens-book-publishers'
    | '/contact'
    | '/get-a-quote'
    | '/ghost-writing'
    | '/our-story'
    | '/portfolio'
    | '/publish-book'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/audiobook'
    | '/author-website'
    | '/book-cover-design'
    | '/book-editing'
    | '/book-formatting'
    | '/book-illustration'
    | '/book-marketing'
    | '/book-printing'
    | '/book-video-trailer'
    | '/childrens-book-publishers'
    | '/contact'
    | '/get-a-quote'
    | '/ghost-writing'
    | '/our-story'
    | '/portfolio'
    | '/publish-book'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudiobookRoute: typeof AudiobookRoute
  AuthorWebsiteRoute: typeof AuthorWebsiteRoute
  BookCoverDesignRoute: typeof BookCoverDesignRoute
  BookEditingRoute: typeof BookEditingRoute
  BookFormattingRoute: typeof BookFormattingRoute
  BookIllustrationRoute: typeof BookIllustrationRoute
  BookMarketingRoute: typeof BookMarketingRoute
  BookPrintingRoute: typeof BookPrintingRoute
  BookVideoTrailerRoute: typeof BookVideoTrailerRoute
  ChildrensBookPublishersRoute: typeof ChildrensBookPublishersRoute
  ContactRoute: typeof ContactRoute
  GetAQuoteRoute: typeof GetAQuoteRoute
  GhostWritingRoute: typeof GhostWritingRoute
  OurStoryRoute: typeof OurStoryRoute
  PortfolioRoute: typeof PortfolioRoute
  PublishBookRoute: typeof PublishBookRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiobook': {
      id: '/audiobook'
      path: '/audiobook'
      fullPath: '/audiobook'
      preLoaderRoute: typeof AudiobookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author-website': {
      id: '/author-website'
      path: '/author-website'
      fullPath: '/author-website'
      preLoaderRoute: typeof AuthorWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-cover-design': {
      id: '/book-cover-design'
      path: '/book-cover-design'
      fullPath: '/book-cover-design'
      preLoaderRoute: typeof BookCoverDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-editing': {
      id: '/book-editing'
      path: '/book-editing'
      fullPath: '/book-editing'
      preLoaderRoute: typeof BookEditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-formatting': {
      id: '/book-formatting'
      path: '/book-formatting'
      fullPath: '/book-formatting'
      preLoaderRoute: typeof BookFormattingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-illustration': {
      id: '/book-illustration'
      path: '/book-illustration'
      fullPath: '/book-illustration'
      preLoaderRoute: typeof BookIllustrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-marketing': {
      id: '/book-marketing'
      path: '/book-marketing'
      fullPath: '/book-marketing'
      preLoaderRoute: typeof BookMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-printing': {
      id: '/book-printing'
      path: '/book-printing'
      fullPath: '/book-printing'
      preLoaderRoute: typeof BookPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-video-trailer': {
      id: '/book-video-trailer'
      path: '/book-video-trailer'
      fullPath: '/book-video-trailer'
      preLoaderRoute: typeof BookVideoTrailerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/childrens-book-publishers': {
      id: '/childrens-book-publishers'
      path: '/childrens-book-publishers'
      fullPath: '/childrens-book-publishers'
      preLoaderRoute: typeof ChildrensBookPublishersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-a-quote': {
      id: '/get-a-quote'
      path: '/get-a-quote'
      fullPath: '/get-a-quote'
      preLoaderRoute: typeof GetAQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghost-writing': {
      id: '/ghost-writing'
      path: '/ghost-writing'
      fullPath: '/ghost-writing'
      preLoaderRoute: typeof GhostWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish-book': {
      id: '/publish-book'
      path: '/publish-book'
      fullPath: '/publish-book'
      preLoaderRoute: typeof PublishBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudiobookRoute: AudiobookRoute,
  AuthorWebsiteRoute: AuthorWebsiteRoute,
  BookCoverDesignRoute: BookCoverDesignRoute,
  BookEditingRoute: BookEditingRoute,
  BookFormattingRoute: BookFormattingRoute,
  BookIllustrationRoute: BookIllustrationRoute,
  BookMarketingRoute: BookMarketingRoute,
  BookPrintingRoute: BookPrintingRoute,
  BookVideoTrailerRoute: BookVideoTrailerRoute,
  ChildrensBookPublishersRoute: ChildrensBookPublishersRoute,
  ContactRoute: ContactRoute,
  GetAQuoteRoute: GetAQuoteRoute,
  GhostWritingRoute: GhostWritingRoute,
  OurStoryRoute: OurStoryRoute,
  PortfolioRoute: PortfolioRoute,
  PublishBookRoute: PublishBookRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
